-- local sys = require("santoku.system")
-- local str = require("santoku.string")
-- local atom = sys.atom()

-- local vals = {}
-- for i = 1, 100 do
--   vals[i] = i
-- end

-- for data in sys.sh({
--   jobs = 16,
--   fn = function (job)
--     while true do
--       local a = atom()
--       sys.sleep(0.1)
--       if a > #vals then
--         break
--       else
--         print(job, a, vals[a])
--       end
--     end
--   end
-- }) do
--   local n, a, v = str.match(data, "(%d+)\t(%d+)\t(%d+)")
--   print(">", n, a, v)
-- end
